### ISSUE TITLE
If b is an array of Integers, doesn't work.

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Krylov.jl#17] opened 2017-01-17 20:14 UTC
~~Not sure which changes yet, but it stopped working.~~

**Comment by abelsiqueira** [comment] 2017-01-17 20:18
Shame on me. It failed because I used a matrix with integer values. Will investigate further, though.

**Comment by dpo** [comment] 2017-01-17 22:19
What doesn't work exactly?

**Comment by abelsiqueira** [comment] 2017-01-17 23:12
It looks like `BLAS.dot` only accept floats. I see three solutions:

- Change `BLAS.dot` to `dot`;
- Change the type of `b` from `Array{T,1}` to `Array{Float64,1}`, so that it really won't work for `Array{Int,1}`, but it will be clearer where;
- Change `r = copy(b)` to `r = 1.0*b`.

**Comment by dpo** [comment] 2017-01-17 23:18
Yes, BLAS is only float32, float64, complex64 and complex128. In my tests, `BLAS.dot` can be much faster than `dot`, but things might have changed. I think `b` should be declared `Vector{T}` with `T <: Real`. If the user's `b` is integer, we should convert it to float64.

**Comment by abelsiqueira** [comment] 2017-01-17 23:21
In that case, the third option works well. I'll implement and make a PR.

**Comment by dpo** [comment] 2017-01-17 23:24
Note (for the future) that there are disadvantages to using `BLAS.dot`:
1. vectors must be contiguous; you can't use non-contiguous slices
2. the implementation doesn't generalize to multiple right-hand sides.

Maybe it's time to benchmark `dot` again.

**Comment by abelsiqueira** [comment] 2017-01-18 00:15
Code: https://gist.github.com/abelsiqueira/23148a392462c2d7a07fbdb1f943119f
![blas_bench](https://cloud.githubusercontent.com/assets/1068752/22045555/16a2b984-dd02-11e6-9381-a11312c66388.png)
> Minimum, mean and maximum times

![blas_bench2](https://cloud.githubusercontent.com/assets/1068752/22045556/16a43fde-dd02-11e6-9aa7-49e1f66a61dd.png)
> BLAS.dot time/dot time. Greater than 1 means that BLAS.dot is that much faster.

Looks like `BLAS.dot` is much better for small problems.

**Comment by dpo** [comment] 2017-01-18 01:10
Many thanks for that! So `BLAS.dot` remains very much relevant.

**Comment by dpo** [comment] 2017-01-18 17:10
What BLAS are you using?

**Comment by abelsiqueira** [comment] 2017-01-18 17:13
The default. I think that's OpenBLAS.

**Comment by dpo** [comment] 2017-01-18 17:21
It must be better tuned than mine because if I try to reproduce your experiment, BLAS.dot and dot are pretty much the same at size 100 or even less.

**Comment by dpo** [comment] 2017-01-21 02:01
Fixed in #18.

**Closed by dpo** 2017-01-21 02:01 UTC

**Comment by dpo** [comment] 2017-01-22 18:22
In the same vein, I'm noticing (with my BLAS) that
- `BLAS.dot(x, y)` (as opposed to `BLAS.dot(n, x, 1, y, 1)`) has the same performance as `dot(x,y)`
- all `BLAS.nrm2(x,y)`, `BLAS.nrm2(n, x, 1)` and `norm(x)` have similar performance.

I modified your script: https://gist.github.com/272c500b0e0a8557682378b6924aeb48

**Comment by abelsiqueira** [comment] 2017-01-22 18:41
My results (changed to 15)
![blas dot_blas dot simple _dot_ratio](https://cloud.githubusercontent.com/assets/1068752/22184863/99e7f634-e0c1-11e6-85ee-3cf879730954.png)
![blas dot_vs_blas dot simple _vs_dot](https://cloud.githubusercontent.com/assets/1068752/22184864/99e8193e-e0c1-11e6-8c3a-d9e028303fb3.png)
![blas nrm2_blas nrm2 simple _norm_ratio](https://cloud.githubusercontent.com/assets/1068752/22184862/99e7a012-e0c1-11e6-829b-9ca4c6ba68c2.png)
![blas nrm2_vs_blas nrm2 simple _vs_norm](https://cloud.githubusercontent.com/assets/1068752/22184865/99e85354-e0c1-11e6-98f9-bd84d03d1667.png)

**Comment by dpo** [comment] 2017-01-22 18:50
I observe the same with `nrm2`. My statement above was incorrect. I fixed it.

**Comment by abelsiqueira** [comment] 2017-01-22 19:28
Looking at
https://github.com/JuliaLang/julia/blob/v0.5.0/base/linalg/blas.jl
and
https://github.com/JuliaLang/julia/blob/v0.5.0/base/linalg/generic.jl
I found that
- `dot` is sufficiently more complicated than `BLAS.dot`
- `BLAS.dot` simple should be slightly more complicated that `BLAS.dot`
- `norm` is sufficiently more complicated than `BLAS.nrm2`
- `BLAS.nrm2` simple should be slightly more complicated that `BLAS.nrm2`
- `BLAS.nrm2` is simpler that `BLAS.dot` simple
- `BLAS.dot` simple uses parametric types, while `BLAS.nrm2` simple doesn't.

**Comment by abelsiqueira** [comment] 2017-01-22 19:53
I think nobody has gone to the trouble of doing this (or other upgrades on BLAS) because of the relative small performance gain versus the trouble of doing it. But it's at least worth investigating or mentioning on the discourse or the issues.
